id: bugIssueLifecycleManagement
name: GitOps.PullRequestIssueManagement
description: Manage lifecycle of issues labeled as bugs
owner: Azure/aks-pm
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: Stale any open bugs that have 30 days inactivity - runs every 6 hours
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isIssue
      - isOpen
      - noActivitySince:
          days: 30
      - or:
        - isNotLabeledWith:
            label: stale
        - isNotLabeledWith:
            label: Under Investigation
      - hasLabel:
          label: bug
      actions:
      - addLabel:
          label: stale
      - addReply:
          reply: This issue has been automatically marked as stale because it has not had any activity for **30 days**. It will be closed if no further activity occurs **within 7 days of this comment**. ${assignees}
    - description: Stale any issues with "Needs Author Feedback" label after 7 days of no activity from author.
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isIssue
      - isOpen
      - noActivitySince:
          days: 7
      - isNotLabeledWith:
          label: stale
      - hasLabel:
          label: bug
      - hasLabel:
          label: Needs Author Feedback
      actions:
      - addLabel:
          label: stale
      - addReply:
          reply: This issue has been automatically marked as stale because it has not had any activity from the author for **7 days**. It will be closed if no further activity occurs **within 7 days of this comment**. ${issueAuthor}
    eventResponderTasks:
      - description: When an issue is labeled with 'SR-Support Request', add a reply with instructions on how to create a support ticket.
        if:
          - payloadType: Issues
          - labelAdded:
              label: SR-Support Request
          - isOpen
        then:
          - addLabel:
              label: Needs Author Feedback
          - addReply:
              reply: >-
                Hi there :wave: AKS bot here. This issue has been tagged as needing a support request so that the AKS support and engineering teams have a look into this particular cluster/issue.


                Follow the steps [here](https://azure.microsoft.com/support/create-ticket/) to create a support ticket for Azure Kubernetes Service and the cluster discussed in this issue.


                Please do mention this issue in the case description so our teams can coordinate to help you. When you have created the support ticket, please add the case number as a comment to this issue to help us with tracking.  


                Thank you!
      - description: If a new comment containing 'Released/Shipped/Fixed on release' is added to a bug', add the resolution labels. 
        if:
          - payloadType: Issue_Comment
          - isOpen
          - hasLabel:
              label: bug
          - commentContains:
              pattern: Released/Shipped/Fixed on release
              isRegex: False
        then:
          - addLabel:
              label: resolution/fix-released
          - addLabel:
              label: resolution/shipped
      - description: When a bug fix is in progress, notify the customer with a message.
        if:
          - payloadType: Issues
          - labelAdded:
              label: Fix in Progress
          - isOpen
        then:
          - addReply:
              reply: >-
                Hi there :wave: AKS bot here. Thank you for reporting this bug to the AKS team. This issue has been tagged as the bug fix is currently in progress. When the fix is complete, we will update you with the investigation and fix details.
      - description: When a bug is being investigated, notify the customer with a message.
        if:
          - payloadType: Issues
          - labelAdded:
              label: Under Investigation
          - isOpen
        then:
          - addReply:
              reply: >-
                Hi there :wave: AKS bot here. This issue has been tagged as being investigated by the AKS team. Please check back shortly to see if any additional information or actions are needed from you. Thank you!
onFailure: 
onSuccess:
