id: 
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner: 
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: 
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: stale
      - noActivitySince:
          days: 7
      actions:
      - closeIssue
      - addReply:
          reply: This issue will now be closed because it hasn't had any activity for 7 days after stale. ${issueAuthor} feel free to comment again on the next 7 days to reopen or open a new issue after that time if you still have a question/issue or suggestion.
    - description: 
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isIssue
      - isOpen
      - noActivitySince:
          days: 60
      - isNotLabeledWith:
          label: stale
      - isNotLabeledWith:
          label: feature-request
      - isNotLabeledWith:
          label: bug
      actions:
      - addLabel:
          label: stale
      - addReply:
          reply: This issue has been automatically marked as stale because it has not had any activity for **60 days**. It will be closed if no further activity occurs **within 15 days of this comment**.
    - description: 
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: resolution/duplicate
      - noActivitySince:
          days: 1
      actions:
      - addReply:
          reply: This issue has been marked as duplicate and has not had any activity for **1 day**. It will be closed for housekeeping purposes.
      - closeIssue
    - description: 
      frequencies:
      - daily:
          time: 9:0
      - daily:
          time: 12:0
      - daily:
          time: 15:0
      - daily:
          time: 18:0
      filters:
      - isOpen
      - hasLabel:
          label: action-required
      - noActivitySince:
          days: 5
      - isNotLabeledWith:
          label: Needs Author Feedback
      - isNotLabeledWith:
          label: Needs Information
      - isNotLabeledWith:
          label: 'Needs Attention :wave:'
      - isNotAssigned
      actions:
      - addReply:
          reply: Action required from @Azure/aks-pm
      - addLabel:
          label: 'Needs Attention :wave:'
    - description: 
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isOpen
      - hasLabel:
          label: triage
      - noActivitySince:
          days: 2
      - isNotLabeledWith:
          label: action-required
      actions:
      - addLabel:
          label: action-required
      - addReply:
          reply: Triage required from @Azure/aks-pm ${assignees}
    - description: 
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isOpen
      - hasLabel:
          label: 'Needs Attention :wave:'
      - noActivitySince:
          days: 15
      - isNotLabeledWith:
          label: Needs Information
      - isNotLabeledWith:
          label: Needs Author Feedback
      actions:
      - addReply:
          reply: Issue needing attention of @Azure/aks-leads
    - description: 
      frequencies:
      - weekday:
          day: Wednesday
          time: 11:0
      filters:
      - isOpen
      - isNotAssigned
      - hasNoLabel
      actions:
      - addReply:
          reply: '@Azure/aks-pm issue needs labels'
    - description: 
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isOpen
      - isNotLabeledWith:
          label: triage
      - isNotLabeledWith:
          label: Needs Information
      - isNotLabeledWith:
          label: action-required
      - isNotLabeledWith:
          label: announcement
      - isNotLabeledWith:
          label: awareness
      - isNotLabeledWith:
          label: feature-request
      - isNotLabeledWith:
          label: wontfix
      - isNotLabeledWith:
          label: Feedback
      - isNotLabeledWith:
          label: enhancement
      - isNotLabeledWith:
          label: resolution/fix-released
      - noActivitySince:
          days: 25
      - isNotLabeledWith:
          label: service-updates
      - isNotLabeledWith:
          label: resolution/shipped
      actions:
      - addLabel:
          label: action-required
    - description: 
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isOpen
      - hasLabel:
          label: feature-request
      - noActivitySince:
          days: 180
      actions:
      - addLabel:
          label: action-required
    - description: 
      frequencies:
      - daily:
          time: 1:0
      filters:
      - isOpen
      - hasLabel:
          label: Needs Information
      - noActivitySince:
          days: 7
      actions:
      - addLabel:
          label: stale
    - description: 
      frequencies:
      - daily:
          time: 1:0
      filters:
      - isOpen
      - hasLabel:
          label: Needs Author Feedback
      - noActivitySince:
          days: 7
      actions:
      - addLabel:
          label: stale
    - description: 
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isOpen
      - hasLabel:
          label: resolution/answer-provided
      - noActivitySince:
          days: 2
      actions:
      - addReply:
          reply: Thanks for reaching out. I'm closing this issue as it was marked with "Answer Provided" and it hasn't had activity for 2 days.
      - closeIssue
    - description: 
      frequencies:
      - hourly:
          hour: 12
      filters:
      - isOpen
      - hasLabel:
          label: resolution/fix-released
      - noActivitySince:
          days: 7
      actions:
      - addReply:
          reply: Thanks for reaching out. I'm closing this issue as it was marked with "Fix released" and it hasn't had activity for 7 days.
      - closeIssue
    - description: 
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isOpen
      - hasLabel:
          label: SR-Support Request
      - isNotLabeledWith:
          label: bug
      - noActivitySince:
          days: 7
      - isNotLabeledWith:
          label: feature-request
      - isNotLabeledWith:
          label: stale
      actions:
      - addLabel:
          label: stale
      - addReply:
          reply: Case being worked with Microsoft Support, adding stale label for automatic closure if not other reports are added.
    - description: 
      frequencies:
      - hourly:
          hour: 12
      filters:
      - isOpen
      - hasLabel:
          label: resolution/shipped
      - noActivitySince:
          days: 7
      actions:
      - addReply:
          reply: Thank you for the feature request. I'm closing this issue as this feature has shipped and it hasn't had activity for 7 days.
      - closeIssue
    - description: 
      frequencies:
      - hourly:
          hour: 12
      filters:
      - isOpen
      - hasLabel:
          label: resolution/other
      - noActivitySince:
          days: 3
      actions:
      - addReply:
          reply: Thanks for reaching out. I'm closing this issue as it was marked resolved and it hasn't had activity for 3 days. If it continues please reply or open a support ticket.
      - closeIssue
    eventResponderTasks:
    - if:
      - payloadType: Issue_Comment
      - isAction:
          action: Created
      - isActivitySender:
          issueAuthor: True
      - isOpen
      - or:
        - hasLabel:
            label: Needs Information
        - hasLabel:
            label: Needs Author Feedback
      then:
      - addLabel:
          label: action-required
      - removeLabel:
          label: Needs Author Feedback
      - removeLabel:
          label: Needs Information
      description: 
    - if:
      - payloadType: Issues
      - not:
          isAction:
            action: Closed
      - hasLabel:
          label: stale
      - not:
          labelAdded:
            label: stale
      then:
      - removeLabel:
          label: stale
      description: 
    - if:
      - payloadType: Issue_Comment
      - hasLabel:
          label: stale
      then:
      - removeLabel:
          label: stale
      description: 
    - if:
      - payloadType: Issues
      - labelAdded:
          label: SR-Support Request
      - isOpen
      then:
      - addReply:
          reply: >-
            Hi there :wave: AKS bot here. This issue has been tagged as needing a support request so that the AKS support and engineering teams have a look into this particular cluster/issue.


            Follow the steps [here](https://azure.microsoft.com/en-us/support/create-ticket/) to create a support ticket for Azure Kubernetes Service and the cluster discussed in this issue.


            Please do mention this issue in the case description so our teams can coordinate to help you.


            Thank you!
      description: 
    - if:
      - or:
        - payloadType: Issues
      - isAction:
          action: Opened
      then:
      - if:
        - hasLabel:
            label: addon/container-insights
        then:
        - mentionUsers:
            mentionees:
            - vishiy
            - saaror
            replyTemplate: ${mentionees} would you be able to assist?
            assignMentionees: False
      - if:
        - hasLabel:
            label: addon/policy
        then:
        - mentionUsers:
            mentionees:
            - az-policy-kube
            replyTemplate: ${mentionees} would you be able to assist?
            assignMentionees: False
      - if:
        - hasLabel:
            label: addon/virtual-nodes
        then:
        - mentionUsers:
            mentionees:
            - peterpogorski
            - justindavies
            replyTemplate: ${mentionees} would you be able to assist?
            assignMentionees: False
      - if:
        - hasLabel:
            label: addon/k8s-dashboard
        then:
        - mentionUsers:
            mentionees:
            - qpetraroia
            replyTemplate: ${mentionees} would you be able to assist?
            assignMentionees: True
      - if:
        - hasLabel:
            label: azure/http-app-routing
        then:
        - mentionUsers:
            mentionees:
            - qpetraroia
            replyTemplate: ${mentionees} would you be able to assist?
            assignMentionees: True
      - if:
        - hasLabel:
            label: azure/application-gateway
        then:
        - mentionUsers:
            mentionees:
            - akshaysngupta
            - mscatyao
            replyTemplate: ${mentionees} would you be able to assist?
            assignMentionees: False
      - if:
        - hasLabel:
            label: azure/security-center
        then:
        - mentionUsers:
            mentionees:
            - mayaherskovic
            replyTemplate: ${mentionees} would you be able to assist?
            assignMentionees: False
      - if:
        - hasLabel:
            label: azure/acr
        then:
        - mentionUsers:
            mentionees:
            - SteveLasker
            replyTemplate: ${mentionees} would you be able to assist?
            assignMentionees: False
      - if:
        - hasLabel:
            label: azure/confidentialCompute
        then:
        - mentionUsers:
            mentionees:
            - agowdamsft
            replyTemplate: ${mentionees} would you be able to assist?
            assignMentionees: False
      - if:
        - hasLabel:
            label: azure/portal
        then:
        - mentionUsers:
            mentionees:
            - Azure/aks-portal
            replyTemplate: ${mentionees} would you be able to assist?
            assignMentionees: False
      - if:
        - hasLabel:
            label: AzGov
        then:
        - mentionUsers:
            mentionees:
            - miwithro
            replyTemplate: ${mentionees} would you be able to assist?
            assignMentionees: False
      - if:
        - hasLabel:
            label: networking/azcni
        then:
        - mentionUsers:
            mentionees:
            - aanandr
            - phealy
            replyTemplate: ${mentionees} would you be able to assist?
            assignMentionees: False
      - if:
        - hasLabel:
            label: pod-identity
        then:
        - mentionUsers:
            mentionees:
            - miwithro
            replyTemplate: ${mentionees} would you be able to assist?
            assignMentionees: False
      - if:
        - hasLabel:
            label: windows
        then:
        - mentionUsers:
            mentionees:
            - immuzz
            - justindavies
            replyTemplate: ${mentionees} would you be able to assist?
            assignMentionees: False
      - if:
        - hasLabel:
            label: storage
        then:
        - mentionUsers:
            mentionees:
            - azure/azure-container-storage-team
            replyTemplate: ${mentionees} would you be able to assist?
            assignMentionees: False
      - if:
        - hasLabel:
            label: azure/oms
        then:
        - mentionUsers:
            mentionees:
            - vishiy
            - saaror
            replyTemplate: ${mentionees} would you be able to assist?
            assignMentionees: False
      - if:
        - hasLabel:
            label: azure/log-analytics
        then:
        - mentionUsers:
            mentionees:
            - vishiy
            - saaror
            replyTemplate: ${mentionees} would you be able to assist?
            assignMentionees: False
      - if:
        - hasLabel:
            label: AzChina
        then:
        - mentionUsers:
            mentionees:
            - miwithro
            replyTemplate: ${mentionees} would you be able to assist?
            assignMentionees: False
      - if:
        - hasLabel:
            label: addon/agic
        then:
        - mentionUsers:
            mentionees:
            - akshaysngupta
            - mscatyao
            replyTemplate: ${mentionees} would you be able to assist?
            assignMentionees: False
      - if:
        - hasLabel:
            label: azure/policy
        then:
        - mentionUsers:
            mentionees:
            - az-policy-kube
            replyTemplate: ${mentionees} would you be able to assist?
            assignMentionees: False
      - if:
        - hasLabel:
            label: upstream/helm
        then:
        - mentionUsers:
            mentionees:
            - squillace
            - bridgetkromhout
            replyTemplate: ${mentionees} would you be able to assist?
            assignMentionees: False
      - if:
        - hasLabel:
            label: upstream/gatekeeper
        then:
        - mentionUsers:
            mentionees:
            - sozercan
            - ritazh
            replyTemplate: ${mentionees} would you be able to assist?
            assignMentionees: False
      - if:
        - hasLabel:
            label: client/portal
        then:
        - mentionUsers:
            mentionees:
            - Azure/aks-portal
            replyTemplate: ${mentionees} would you be able to assist?
            assignMentionees: False
      - if:
        - hasLabel:
            label: service-mesh
        then:
        - mentionUsers:
            mentionees:
            - azure/aks-traffic
            replyTemplate: ${mentionees} would you be able to assist?
            assignMentionees: True
      description:
    - if:
      - isAction:
            action: Labeled
      - hasLabel:
            label: aks/test
      then:
        - mentionUsers:
            mentionees:
            - aritraghosh
            - julia-yin
            - AllenWen-at-Azure
            replyTemplate: ${mentionees} would you be able to assist?
            assignMentionees: true      
      description: 
    - if:
      - payloadType: Issues
      - isAssignedToSomeone
      - labelAdded:
          label: action-required
      - not:
          hasLabel:
            label: Needs Information
      - not:
          hasLabel:
            label: Needs Author Feedback
      then:
      - addReply:
          reply: Action required from ${assignees}.
      description: 
    - if:
      - payloadType: Issues
      - isOpen
      - or:
        - hasLabel:
            label: 'Needs Attention :wave:'
        - hasLabel:
            label: action-required
      - or:
        - activitySenderHasPermission:
            permission: Write
        - activitySenderHasAssociation:
            association: Owner
        - activitySenderHasAssociation:
            association: Contributor
        - activitySenderHasAssociation:
            association: Collaborator
        - activitySenderHasPermission:
            permission: Admin
        - activitySenderHasAssociation:
            association: Member
        - isAction:
            action: Labeled
        - isAction:
            action: Unlabeled
        - isAction:
            action: Null
      then:
      - removeLabel:
          label: action-required
      - removeLabel:
          label: 'Needs Attention :wave:'
      description: 
    - if:
      - payloadType: Issue_Comment
      - isOpen
      - or:
        - activitySenderHasPermission:
            permission: Admin
        - activitySenderHasPermission:
            permission: Write
        - activitySenderHasAssociation:
            association: Collaborator
        - activitySenderHasAssociation:
            association: Owner
        - activitySenderHasAssociation:
            association: Contributor
        - activitySenderHasAssociation:
            association: Member
      - or:
        - hasLabel:
            label: 'Needs Attention :wave:'
        - hasLabel:
            label: action-required
      then:
      - removeLabel:
          label: action-required
      - removeLabel:
          label: 'Needs Attention :wave:'
      description: 
    - if:
      - payloadType: Issue_Comment
      - isOpen
      - not:
          hasLabel:
            label: bug
      - commentContains:
          pattern: Released/Shipped/Fixed on release
          isRegex: False
      then:
      - addLabel:
          label: resolution/shipped
      description: 
    - if:
      - payloadType: Issue_Comment
      - isOpen
      - hasLabel:
          label: bug
      - commentContains:
          pattern: Released/Shipped/Fixed on release
          isRegex: False
      then:
      - addLabel:
          label: resolution/fix-released
      description: 
onFailure: 
onSuccess: 
