apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: rdma-training-mellanox
  labels:
    app.kubernetes.io/part-of: distributed-training-rdma
    aks-codelab: distributed-training-rdma
spec:
  rules:
  - name: rdma-training-mellanox
    labels:
      feature.node.kubernetes.io/pci-15b3.present: "true"
    matchFeatures:
    - feature: pci.device
      matchExpressions:
        # ConnectX devices used by Azure ND A100/H100/H200 SKUs.
        device: {op: In, value: ["101c", "101e"]}
