apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/ingress-controller

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory # the ACME server production URL
    email: your-email-addr@domain.com # email address used for ACME registration
    privateKeySecretRef: # name of a secret used to store the ACME account private key
      name: letsencrypt-prod
    solvers:
      - http01: # enable HTTP-01 challenge provider
          ingress:
            ingressClassName: istio
