# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "AKS Engineering Blog"
email: brian.redmond@microsoft.com
description: >- # this means to ignore newlines until "baseurl:"
  "Insights and best practices from the AKS Engineering Team"
#baseurl: "/AKS" # the subpath of your site, e.g. /blog
twitter_username: theakscommunity
github_username:  theakscommunity
logo: "/assets/images/400x400.png"
permalink: /:year/:month/:day/:title
search: true 

# Google Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "<GTAG_ID>"
    anonymize_ip: false # default

# Site theme and skin
remote_theme: "mmistakes/minimal-mistakes@4.26.0"
minimal_mistakes_skin: neon
og_image: /assets/images/400x400.png

# Build settings
include: ["_pages"]

# Jekyll plugins
plugins:
  - jekyll-feed
  - jekyll-target-blank
  - jekyll-include-cache

enable_copy_code_button: true

## Default front matter
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      sidebar:
        nav: "side"
      classes: wide
  - scope:
      path: ""
      type: pages
    values:
      sidebar:
        nav: "side"
      classes: wide

# Footer links that get rendered via _includes/footer.html
# https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/footer.html
footer:
  links:
    - url: "mailto:brian.redmond@microsoft.com"
      icon: "fas fa-envelope"
      label: "Mail"
    - url: "https://github.com/Azure/AKS"
      icon: "fab fa-fw fa-github"
      label: "GitHub"
    - url: "https://twitter.com/theakscommunity"
      icon: "fab fa-fw fa-twitter"
      label: "X"
    - url: "https://www.youtube.com/@theakscommunity"
      icon: "fab fa-fw fa-youtube"
      label: "YouTube"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
