apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bookinfo-letsencrypt-certs
  namespace: aks-istio-ingress
spec:
  secretName: bookinfo-certs # letsencrypt certificate secret name, should match the credentialName in the gateway resource
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: test.dev.azureservicemesh.io
  dnsNames:
    - test.dev.azureservicemesh.io # this should match a host name in the gateway resource
