name: markdown-linter

on:
  pull_request:
    branches: [master]
    paths:
      - "blog/**"

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        file: ${{ github.event.pull_request.changed_files }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@v7.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MARKDOWN_CONFIG_FILE: .github/linters/markdown.yml
          VALIDATE_MARKDOWN: true
          VALIDATE_MARKDOWN_PRETTIER: true
          FILTER_REGEX_INCLUDE: ${{ matrix.file }}
