name: Check website build and markdown

on:
  pull_request:
    branches: [master]
    paths:
      - "website/blog/**.md"

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  build-website:
    name: Build website
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: website/package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Build website
        run: npm run build

  get-files-changed:
    name: Get changed markdown files
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.files.outputs.files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0

      - name: Get changed files
        id: files
        run: |
          files=$(git diff --name-only HEAD^1 HEAD | grep 'website/blog/.*\.md' || true)
          if [ -z "$files" ]; then
            echo "files=[]" >> $GITHUB_OUTPUT
          else
            json_array=$(echo "$files" | jq -R -s -c 'split("\n") | map(select(length > 0))')
            echo "files=$json_array" >> $GITHUB_OUTPUT
          fi
          printf "Changed files: %s\n" "$files"

  run-markdown-lint:
    name: Run markdown linter
    runs-on: ubuntu-latest
    needs: get-files-changed

    strategy:
      fail-fast: false
      matrix:
        file: ${{ fromJson(needs.get-files-changed.outputs.files) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter/slim@ffde3b2b33b745cb612d787f669ef9442b1339a6 # v8.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_MARKDOWN: true
          LINTER_RULES_PATH: website/blog/linters
          FILTER_REGEX_INCLUDE: ${{ matrix.file }}
